// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Image
{
    public int ImageId { get; set; }

    public int? ProductId { get; set; }

    public string Url { get; set; }

    public bool IsMain { get; set; }

    public virtual Product Product { get; set; }
}