// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class ProductMonthConfig
{
    public int ConfigId { get; set; }

    public int ProductId { get; set; }

    public int? MonthNumber { get; set; }

    public bool? IsAvailable { get; set; }

    public decimal? SpecialPrice { get; set; }

    public virtual Product Product { get; set; }
}